import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function game(){const context=vm.createContext({location:{protocol:'http:'},localStorage:{getItem:()=>null,setItem:()=>{}},document:{addEventListener:()=>{}},Date,Math:Object.assign(Object.create(Math),{random:()=>.5}),JSON,fetch:()=>Promise.resolve({}),console});const source=readFileSync('public/index.html','utf8').match(/<script type="module">([\s\S]*?)<\/script>/)[1].split('setInterval(()=>')[0];vm.runInContext(source,context);vm.runInContext('render=()=>{}',context);return code=>vm.runInContext(code,context)}
test('offline earnings run at half rate and respect capacity',()=>{const run=game();run('s.workers.wood={xp:0};s.last=Date.now()-60000;accrue()');assert.ok(Math.abs(run('s.wood')-30)<.1);run('s.last=Date.now()-3600000;accrue()');assert.equal(run('s.wood'),100)});
test('loan interest applies every five expeditions without compounding',()=>{const run=game();run('s.debt=100;s.interest=10');for(let i=0;i<5;i++)run('battle={loot:{gold:0,wood:0,stone:0,food:0,iron:0,rivets:0,blueprints:0}};finish(true)');assert.equal(run('s.interest'),11);assert.equal(run('s.debt'),100);assert.equal(run('s.loanRuns'),0)});
test('free recovery completes after its deadline',()=>{const run=game();run('s.heroDead=true;s.recover=Date.now()+300000;accrue()');assert.equal(run('s.heroDead'),true);run('s.recover=Date.now()-1;accrue()');assert.equal(run('s.heroDead'),false);assert.equal(run('s.recover'),0)});

test('ten slots, minimal starter equipment, and legacy equipment migration',()=>{const run=game();assert.equal(run('SLOTS.length'),10);assert.equal(run('SLOTS.filter(x=>s.gear[x.key]>=0).length'),4);assert.equal(run('SLOTS.some(x=>x.key==="arrows")'),false);run('s=migrate({...s,gear:{weapon:2,armor:3},gearUpgrades:{weapon:1,armor:2}})');assert.equal(run('s.gear.body'),3);assert.equal(run('s.gearUpgrades.body'),2);assert.equal(run('s.gear.armor'),undefined);});
test('crafted gear raises stats and bonuses affect combat',()=>{const run=game();const base=run('heroStats().attack');run('s.gear.weapon=1;s.gear.ring=2;s.gear.cape=2;s.gear.neck=2');assert.ok(run('heroStats().attack')>base);assert.equal(run('heroStats().crit'),.09);assert.equal(run('heroStats().evade'),.03);assert.equal(run('heroStats().leech'),.03);});
test('storage prices increase with storage level',()=>{const run=game();const first=run('storageCost("wood").wood');run('s.buildings.woodStorage=1');assert.ok(run('storageCost("wood").wood')>first);assert.equal(run('cap("wood")'),250);});
test('battle attacks reduce enemy HP and healers restore living allies',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0},{cls:"Archer",level:1,xp:0},{cls:"Healer",level:1,xp:0}];startBattle({d:0,name:"Test crypt",mod:1});battle.allies[0].hp-=20;battle.beat=1');const before=run('battle.allies[0].hp');run('tickBattle()');assert.ok(run('battle.enemies[0].hp')<run('battle.enemies[0].maxHp'));assert.ok(run('battle.allies[0].hp')>before);assert.ok(run('battle.events.some(e=>e.includes("restores"))'));});
test('hero takes the front line and falling support troops stay dead',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0}];startBattle({d:2,name:"Test crypt",mod:1});battle.enemies=battle.enemies.slice(0,1);battle.enemies[0].hp=1000;tickBattle()');assert.equal(run('battle.allies[1].hp'),run('battle.allies[1].maxHp'));assert.ok(run('battle.allies[0].hp')<run('battle.allies[0].maxHp'));run('battle.allies[1].hp=1;hit(battle.enemies[0],battle.allies[1])');assert.equal(run('s.recruits[0].dead'),true);assert.equal(run('battle.allies[1].hp'),0);});

test('risk estimates simulate combat without changing saved inventory or a live battle',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0}];startBattle({d:0,name:"Live expedition",mod:1});battle.allies[0].hp-=4');const state=run('JSON.stringify(s)'),battle=run('JSON.stringify(battle)');const low=run('chance(0,1)');assert.ok(low>=0&&low<=100);assert.equal(run('JSON.stringify(s)'),state);assert.equal(run('JSON.stringify(battle)'),battle);run('s.gear.weapon=10;s.gear.body=10');assert.ok(run('chance(0,1)')>=low);});

test('hero acts every turn while small support troops act every other turn',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0},{cls:"Archer",level:1,xp:0},{cls:"Healer",level:1,xp:0}];startBattle({d:0,name:"Test",mod:1});battle.enemies[0].hp=1000;battle.enemies[0].maxHp=1000;battle.enemies[0].attack=0;tickBattle()');assert.equal(run('battle.allies[0].event.beat'),1);assert.equal(run('battle.allies[1].event'),undefined);run('tickBattle()');assert.equal(run('battle.allies[1].event.beat'),2);assert.ok(run('battle.allies.slice(1).every(u=>u.attack<battle.allies[0].attack&&u.maxHp<battle.allies[0].maxHp)'));});
