import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function game(){const context=vm.createContext({location:{protocol:'http:'},localStorage:{getItem:()=>null,setItem:()=>{}},document:{addEventListener:()=>{}},Date,Math:Object.assign(Object.create(Math),{random:()=>.5}),JSON,fetch:()=>Promise.resolve({}),console});const source=readFileSync('public/index.html','utf8').match(/<script type="module">([\s\S]*?)<\/script>/)[1].split('setInterval(()=>')[0];vm.runInContext(source,context);vm.runInContext('render=()=>{}',context);return code=>vm.runInContext(code,context)}
test('offline earnings run at half rate and respect capacity',()=>{const run=game();run('s.workers.wood={xp:0};s.last=Date.now()-60000;accrue()');assert.ok(Math.abs(run('s.wood')-30)<.1);run('s.last=Date.now()-3600000;accrue()');assert.equal(run('s.wood'),100)});
test('loan interest applies every five expeditions without compounding',()=>{const run=game();run('s.debt=100;s.interest=10');for(let i=0;i<5;i++)run('battle={loot:{gold:0,wood:0,stone:0,food:0,iron:0,rivets:0,blueprints:0}};finish(true)');assert.equal(run('s.interest'),11);assert.equal(run('s.debt'),100);assert.equal(run('s.loanRuns'),0)});
test('free recovery completes after its deadline',()=>{const run=game();run('s.heroDead=true;s.recover=Date.now()+300000;accrue()');assert.equal(run('s.heroDead'),true);run('s.recover=Date.now()-1;accrue()');assert.equal(run('s.heroDead'),false);assert.equal(run('s.recover'),0)});

test('ten empty starter slots and existing equipment preservation',()=>{const run=game();assert.equal(run('SLOTS.length'),10);assert.equal(run('SLOTS.filter(x=>s.gear[x.key]>=0).length'),0);assert.equal(run('SLOTS.some(x=>x.key==="arrows")'),false);run('s=migrate({...s,gear:{weapon:2,armor:3},gearUpgrades:{weapon:1,armor:2}})');assert.equal(run('s.gear.body'),3);assert.equal(run('s.gearUpgrades.body'),2);assert.equal(run('s.gear.armor'),undefined);});
test('crafted gear raises stats and bonuses affect combat',()=>{const run=game();const base=run('heroStats().attack');run('s.gear.weapon=1;s.gear.ring=2;s.gear.cape=2;s.gear.neck=2');assert.ok(run('heroStats().attack')>base);assert.equal(run('heroStats().crit'),.09);assert.equal(run('heroStats().evade'),.03);assert.equal(run('heroStats().leech'),.03);});
test('storage prices increase with storage level',()=>{const run=game();const first=run('storageCost("wood").wood');run('s.buildings.woodStorage=1');assert.ok(run('storageCost("wood").wood')>first);assert.equal(run('cap("wood")'),250);});
test('battle attacks reduce enemy HP and healers restore living allies',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0},{cls:"Archer",level:1,xp:0},{cls:"Healer",level:1,xp:0}];startBattle({d:0,name:"Test crypt",mod:1});battle.allies[0].hp-=20;battle.enemies[0].attack=0;battle.beat=1');const before=run('battle.allies[0].hp');run('tickBattle()');assert.ok(run('battle.enemies[0].hp')<run('battle.enemies[0].maxHp'));assert.ok(run('battle.allies[0].hp')>before);assert.ok(run('battle.events.some(e=>e.includes("restores"))'));});
test('hero takes the front line and falling support troops stay dead',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0}];startBattle({d:2,name:"Test crypt",mod:1});battle.enemies=battle.enemies.slice(0,1);battle.enemies[0].hp=1000;tickBattle()');assert.equal(run('battle.allies[1].hp'),run('battle.allies[1].maxHp'));assert.ok(run('battle.allies[0].hp')<run('battle.allies[0].maxHp'));run('battle.allies[1].hp=1;hit(battle.enemies[0],battle.allies[1])');assert.equal(run('s.recruits[0].dead'),true);assert.equal(run('battle.allies[1].hp'),0);});

test('risk estimates simulate combat without changing saved inventory or a live battle',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0}];startBattle({d:0,name:"Live expedition",mod:1});battle.allies[0].hp-=4');const state=run('JSON.stringify(s)'),battle=run('JSON.stringify(battle)');const low=run('chance(0,1)');assert.ok(low>=0&&low<=100);assert.equal(run('JSON.stringify(s)'),state);assert.equal(run('JSON.stringify(battle)'),battle);run('s.gear.weapon=10;s.gear.body=10');assert.ok(run('chance(0,1)')>=low);});

test('hero acts every turn while small support troops act every other turn',()=>{const run=game();run('s.recruits=[{cls:"Warrior",level:1,xp:0},{cls:"Archer",level:1,xp:0},{cls:"Healer",level:1,xp:0}];startBattle({d:0,name:"Test",mod:1});battle.enemies[0].hp=1000;battle.enemies[0].maxHp=1000;battle.enemies[0].attack=0;tickBattle()');assert.equal(run('battle.allies[0].event.beat'),1);assert.equal(run('battle.allies[1].event'),undefined);run('tickBattle()');assert.equal(run('battle.allies[1].event.beat'),2);assert.ok(run('battle.allies.slice(1).every(u=>u.attack<battle.allies[0].attack&&u.maxHp<battle.allies[0].maxHp)'));});

test('gear only rolls at fifth-wave milestones, stays unsecured, and survives extraction',()=>{const run=game();run('Math.random=()=>0;startBattle({d:0,name:"Test",mod:1});rewardWave()');assert.equal(run('battle.loot.equipment.length'),0);run('battle.wave=5;rewardWave()');assert.equal(run('battle.loot.equipment.length'),1);assert.equal(run('s.equipmentBag.length'),0);assert.equal(run('s.gear.weapon'),-1);run('finish(true)');assert.equal(run('s.equipmentBag.length'),1);run('equipItem(0)');assert.equal(run('s.gear.weapon'),1);});
test('ordinary loot rolls often produce no gear, blueprints, or materials',()=>{const run=game();run('startBattle({d:0,name:"Test",mod:1});battle.wave=5;rewardWave()');assert.equal(run('battle.loot.equipment.length'),0);assert.equal(run('battle.loot.blueprints'),0);assert.equal(run('battle.loot.iron+battle.loot.rivets+battle.loot.leather+battle.loot.essence'),0);});
test('blueprints cannot create starter gear and upgrade costs scale steeply',()=>{const run=game();run('s.gold=10000;s.blueprints=10;for(const k of Object.keys(s.items))s.items[k]=1000');assert.equal(run('canCraft("weapon")'),false);run('s.gear.weapon=1');assert.equal(run('canCraft("weapon")'),true);const initialGold=run('upgradeCost("weapon").gold'),initialIron=run('upgradeCost("weapon").iron');run('s.gearUpgrades.weapon=2');assert.ok(run('upgradeCost("weapon").gold')>initialGold*2);assert.ok(run('upgradeCost("weapon").iron')>initialIron);});
test('recruits require developed storage and become more expensive',()=>{const run=game();assert.ok(run('recruitCost().wood')>run('cap("wood")'));const first=run('recruitCost().wood');run('s.recruits.push({cls:"Warrior",level:1,xp:0})');assert.ok(run('recruitCost().wood')>first);});
test('wave completion clears attack effects and checkpoints stay idle',()=>{const run=game();run('startBattle({d:0,name:"Test",mod:1});battle.wave=5;battle.allies[0].event={beat:0,kind:"attack",text:"hit"};rewardWave()');assert.equal(run('battle.allies[0].event'),undefined);assert.equal(run('battle.phase'), 'checkpoint');assert.equal(run('unitCard(battle.allies[0]).includes("attacking")'),false);run('tickBattle()');assert.equal(run('battle.beat'),0);});

test('hero and recruit revival prices rise only after successful revivals',()=>{const run=game();run('s.heroDead=true;s.gold=0;s.food=0');assert.equal(run('reviveHero()'),false);assert.equal(run('s.heroRevives'),0);run('s.gold=1000;s.food=1000;reviveHero()');assert.equal(run('s.heroRevives'),1);assert.ok(run('reviveCost().gold')>25);run('s.recruits=[{cls:"Warrior",level:1,dead:true,revives:0}];reviveRecruit(0)');assert.equal(run('s.recruits[0].revives'),1);assert.ok(run('reviveCost(s.recruits[0]).gold')>15);assert.equal(run('reviveRecruit(0)'),false);assert.equal(run('s.recruits[0].revives'),1);});
test('emergency loan uses the current scaled revival cost',()=>{const run=game();run('s.heroRevives=3;s.heroDead=true;s.gold=0;s.food=0');const cost=run('reviveCost().gold+reviveCost().food*2');run('reviveHero(true)');assert.equal(run('s.debt'),cost);assert.equal(run('s.heroRevives'),4);});
test('manual gathering grows with practice and settlement progress but respects storage',()=>{const run=game();const initial=run('gatherYield("wood")');run('s.gatherCounts.wood=25;s.workers.wood={xp:600};s.buildings.woodStorage=2');assert.ok(run('gatherYield("wood")')>initial*2);run('s.wood=399;s.gather={kind:"wood",amount:gatherYield("wood"),end:Date.now()-1};collectGather()');assert.equal(run('s.wood'),400);assert.equal(run('s.gatherCounts.wood'),26);assert.equal(run('collectGather()'),false);});
test('salvage returns rarity-scaled rewards and never removes equipped gear',()=>{const run=game();run('s.gear.weapon=1;s.equipmentBag=[{slot:"weapon",tier:1,upgrade:0,rarity:"common"},{slot:"weapon",tier:1,upgrade:0,rarity:"epic"}]');assert.equal(run('isDuplicate(s.equipmentBag[0],0)'),true);const common=run('salvageReward(s.equipmentBag[0]).gold'),epic=run('salvageReward(s.equipmentBag[1]).gold');assert.ok(epic>common);run('salvageItem(1)');assert.equal(run('s.gold'),epic);assert.equal(run('s.items.essence'),2);assert.equal(run('s.gear.weapon'),1);assert.equal(run('s.equipmentBag.length'),1);});

test('resource income includes prestige and foreman collects only ready tasks',()=>{const run=game();run('s.workers.wood={xp:300};s.meta.prestiges=2;s.foreman=true;s.gather={kind:"wood",amount:12,end:Date.now()+10000}');assert.ok(Math.abs(run('incomeRate("wood")')-1.32)<.001);run('accrue()');assert.notEqual(run('s.gather'),null);run('s.gather.end=Date.now()-1;accrue()');assert.equal(run('s.gather'),null);assert.ok(run('s.wood')>=12);assert.match(run('resourceTooltip("food")'),/revivals/);});
test('recruit specializations and three-piece Gravewarden set affect hero stats',()=>{const run=game();run('s.gear.body=2;s.gear.head=2;s.gear.legs=2');const baseline=run('heroStats()');run('s.recruits=[{cls:"Warrior",level:1},{cls:"Archer",level:1},{cls:"Healer",level:1}]');assert.ok(run('heroStats().defense')>baseline.defense);assert.equal(run('heroStats().crit'),baseline.crit+.03);assert.ok(run('heroStats().health')>=baseline.health+5);run('s.gear.legs=-1');assert.ok(run('heroStats().health')<baseline.health);});
test('dungeon modifiers change enemies, starting HP, and reward quantities',()=>{const run=game();run('startBattle({d:0,mod:1,name:"Normal"})');const hp=run('battle.enemies[0].maxHp');run('startBattle({d:0,mod:1,modifier:"elite",name:"Elite"})');assert.ok(run('battle.enemies[0].maxHp')>hp);run('startBattle({d:0,modifier:"wounded",name:"Wounded"})');assert.ok(run('battle.allies[0].hp')<run('battle.allies[0].maxHp'));run('startBattle({d:0,modifier:"double",name:"Loot"});rewardWave()');assert.equal(run('battle.loot.gold'),14);});
test('prestige resets adventure but preserves talents, permanent bonuses, and lifetime history',()=>{const run=game();assert.equal(run('doPrestige()'),false);run('s.cycleBosses=1;s.history.bosses=1;s.history.runs=10;s.gold=1000;s.gear.weapon=2');assert.equal(run('doPrestige()'),true);assert.equal(run('s.gold'),0);assert.equal(run('s.gear.weapon'),-1);assert.equal(run('s.history.runs'),10);assert.equal(run('s.meta.prestiges'),1);assert.equal(run('s.meta.essence'),5);assert.equal(run('doPrestige()'),false);assert.equal(run('buyTalent("warrior")'),true);assert.equal(run('s.meta.essence'),4);assert.equal(run('s.talents.warrior'),1);assert.ok(run('heroStats().attack')>9);});
test('offline queue only accepts cleared routes and settles once with reduced rewards',()=>{const run=game();assert.equal(run('startQueue(0,1)'),false);run('s.gear.weapon=100;s.gear.body=100;s.clearedDungeons[0]={d:0,mod:1,name:"Cleared"};startQueue(0,1);s.offlineQueue.readyAt=Date.now()-1;resolveQueue()');assert.equal(run('s.offlineQueue'),null);assert.equal(run('s.history.runs'),1);assert.equal(run('s.history.bosses'),1);assert.equal(run('s.gold'),52);run('resolveQueue()');assert.equal(run('s.gold'),52);});

test('settlement support changes actual expedition stats and barracks gates recruitment',()=>{const run=game();const baseline=run('heroStats()');run('s.wood=5000;s.stone=5000;s.food=5000;s.gold=5000');assert.equal(run('hireRecruit("Warrior")'),false);assert.equal(run('buildBarracks()'),false);run('s.workers={wood:{xp:0},stone:{xp:0},food:{xp:0}}');assert.equal(run('buildBarracks()'),false);assert.equal(run('heroStats().attack'),baseline.attack+1);assert.equal(run('heroStats().defense'),baseline.defense+1);assert.equal(run('heroStats().health'),baseline.health+5);run('s.history.best=5');assert.equal(run('buildBarracks()'),true);assert.equal(run('hireRecruit("Warrior")'),false);run('prepareQuarters();prepareQuarters();prepareQuarters()');const gold=run('s.gold');assert.equal(run('hireRecruit("Warrior")'),true);assert.equal(run('s.gold'),gold-150);assert.equal(run('s.recruits.length'),1);assert.equal(run('buildBarracks()'),false);run('startBattle({d:0,mod:1,name:"Support"})');assert.equal(run('battle.allies[0].attack'),baseline.attack+1);assert.equal(run('hireRecruit("Healer")'),false);});

test('reward focus boosts targeted rewards while equipment stays milestone-only',()=>{const run=game();run('startBattle({d:0,name:"Gold",focus:"gold"});rewardWave()');assert.equal(run('battle.loot.gold'),11);run('Math.random=()=>.1;startBattle({d:0,name:"Gear",focus:"equipment"});battle.wave=5;rewardWave()');assert.equal(run('battle.loot.equipment.length'),1);run('startBattle({d:0,name:"Materials",focus:"materials"});rewardWave()');assert.equal(run('battle.loot.iron'),1);assert.equal(run('battle.loot.equipment.length'),0);});
test('recruit names migrate and modest class traits unlock at level five',()=>{const run=game();run('s.recruits=[{cls:"Archer",level:4,xp:19}];s=migrate(s)');assert.equal(run('s.recruits[0].name'),'Mira');assert.equal(run('recruitUnit(s.recruits[0],0).crit'),.06);run('recordRun(true,5,{gold:0},{name:"Crypt",d:0})');assert.equal(run('s.recruits[0].level'),5);assert.equal(run('recruitUnit(s.recruits[0],0).crit'),.08);assert.equal(run('recruitUnit({cls:"Warrior",level:5},0).defense'),3);assert.match(run('s.log[0]'),/class trait unlocked/);});
test('combat reports record actual damage, healing, and final attacker',()=>{const run=game();run('startBattle({d:0,name:"Report"});battle.allies[0].hp=60;healUnit(battle.allies[0],battle.allies[0],3);hit(battle.allies[0],battle.enemies[0]);hit(battle.enemies[0],battle.allies[0])');assert.ok(run('battle.stats.damage.hero')>0);assert.equal(run('battle.stats.healing.hero'),3);assert.ok(run('battle.stats.taken')>0);assert.equal(run('battleReport(false).lastHit.name'),'Bone guard');run('finish(false)');assert.ok(run('s.lastExpedition.report.damage.hero')>0);});

test('armory comparisons rank combat gains without mutating gear and swapped items stay handled',()=>{const run=game();run('s.gear.weapon=2;s.gearRarities.weapon="rare";s.equipmentBag=[{slot:"weapon",tier:1,upgrade:0,rarity:"legendary"},{slot:"weapon",tier:3,upgrade:0,rarity:"common"}]');const before=run('JSON.stringify([s.gear,s.gearUpgrades,s.gearRarities])');assert.equal(run('rankedItems("weapon")[0].index'),1);assert.match(run('comparisonText(itemComparison(s.equipmentBag[0]))'),/−6 attack/);assert.equal(run('JSON.stringify([s.gear,s.gearUpgrades,s.gearRarities])'),before);run('equipItem(1)');assert.equal(run('s.equipmentBag[1].newFind'),false);assert.equal(run('s.gear.weapon'),3);});

test('equipment stacking is capped and double loot cannot duplicate gear',()=>{const run=game();run('s.talents.treasure=5;Math.random=()=>.19;startBattle({d:2,name:"Capped",focus:"equipment",modifier:"double"});battle.wave=5;rewardWave()');assert.equal(run('battle.loot.equipment.length'),0);run('Math.random=()=>0;startBattle({d:2,name:"Single",focus:"equipment",modifier:"double"});battle.wave=5;rewardWave()');assert.equal(run('battle.loot.equipment.length'),1);assert.ok(run('battle.loot.gold')>0);});
test('objectives require cleared waves, safe extraction, and award once without multipliers',()=>{const run=game();run('s.recruits=[{cls:"Healer",name:"Elara",level:1,xp:0,loyalty:0}];startBattle({d:0,name:"Solo",objective:"solo",modifier:"double"});battle.wave=10');assert.equal(run('battle.allies.length'),1);assert.equal(run('battle.allies[0].maxHp'),75);assert.equal(run('awardObjective(battle,true)'),false);run('battle.clearedWave=10');assert.equal(run('awardObjective(battle,false)'),false);assert.equal(run('awardObjective(battle,true)'),true);assert.equal(run('battle.loot.gold'),25);assert.equal(run('awardObjective(battle,true)'),false);run('recordRun(true,10,battle.loot,battle)');assert.equal(run('s.recruits[0].xp'),0);assert.equal(run('s.recruits[0].loyalty'),0);run('startBattle({d:0,name:"Safe",objective:"safe"});battle.clearedWave=10;battle.allies[1].hp=0');assert.equal(run('awardObjective(battle,true)'),false);});
test('bonds grow only with safe returns and stop at a single two-HP bonus',()=>{const run=game();run('s.recruits=[{cls:"Warrior",name:"Aldric",level:1,xp:0,loyalty:29}];recordRun(false,10,{gold:0},{name:"Loss"})');assert.equal(run('s.recruits[0].loyalty'),29);run('recordRun(true,5,{gold:0},{name:"Return"})');assert.equal(run('s.recruits[0].loyalty'),30);assert.equal(run('recruitUnit(s.recruits[0],0).maxHp'),27);assert.match(run('bondStory(s.recruits[0])'),/guard the home/);run('recordRun(true,5,{gold:0},{name:"Again"})');assert.equal(run('s.recruits[0].loyalty'),30);});
test('rescued specialists require extraction and services have costs and caps',()=>{const run=game();run('startBattle({d:0,name:"Rescue"});battle.wave=15;rescueSpecialist(battle)');assert.equal(run('battle.rescue'),'blacksmith');assert.equal(run('settleRescue(battle,false)'),false);assert.equal(run('s.specialists.blacksmith'),undefined);assert.equal(run('settleRescue(battle,true)'),true);assert.equal(run('settleRescue(battle,true)'),false);run('battle=null;s.gear.weapon=1;s.wood=1000;s.stone=1000;s.gold=1000;s.food=0');const cost=run('upgradeCost("weapon")');assert.equal(run('specialistService("blacksmith")'),true);assert.equal(run('upgradeCost("weapon").gold'),Math.ceil(cost.gold*.9));assert.equal(run('upgradeCost("weapon").iron'),cost.iron);assert.equal(run('specialistService("blacksmith")'),false);run('s.specialists.quartermaster=true');assert.equal(run('specialistService("quartermaster")'),true);assert.equal(run('s.food'),25);assert.equal(run('specialistService("quartermaster")'),false);run('s.expeditions++;s.food=90');assert.equal(run('specialistService("quartermaster")'),false);run('startBattle({d:0,name:"Queue",queued:true});battle.wave=15;rescueSpecialist(battle)');assert.equal(run('battle.rescue'),undefined);});

test('infirmary construction consumes both resource sources once per phase',()=>{const run=game();assert.equal(run('startInfirmaryProject()'),false);run('s.buildings.barracks=1;s.wood=5000;s.stone=5000;s.food=5000;s.gold=5000;for(const k of Object.keys(s.items))s.items[k]=100');for(let i=0;i<3;i++){const gold=run('s.gold'),iron=run('s.items.iron');assert.equal(run('startInfirmaryProject()'),true);assert.ok(run('s.gold')<gold);assert.ok(run('s.items.iron')<iron);assert.equal(run('startInfirmaryProject()'),false);assert.equal(run('s.projects.infirmary.stage'),i);run('s.projects.infirmary.until=Date.now()-1;settleInfirmary()');assert.equal(run('s.projects.infirmary.stage'),i+1);}assert.equal(run('infirmaryReady()'),true);assert.equal(run('startInfirmaryProject()'),false);});
test('infirmary checks all ingredients before charging anything',()=>{const run=game();run('s.buildings.barracks=1;s.wood=300;s.stone=250;s.food=100;s.gold=100');assert.equal(run('startInfirmaryProject()'),false);assert.equal(run('s.wood'),300);assert.equal(run('s.gold'),100);});
test('one infirmary bed revives hero and recruits after 60 seconds without costs',()=>{const run=game();run('s.projects.infirmary.stage=3;s.heroDead=true;s.debt=100;s.recruits=[{cls:"Warrior",name:"Aldric",dead:true,revives:0}];s.clearedDungeons[0]={d:0,name:"Cleared",mod:1}');assert.equal(run('admitPatient("hero")'),true);assert.ok(run('s.infirmaryPatient.until-Date.now()')>59000);assert.equal(run('admitPatient(0)'),true);assert.equal(run('admitPatient(0)'),false);assert.equal(run('reviveHero(true)'),false);assert.equal(run('startQueue(0,1)'),false);run('settleInfirmary()');assert.equal(run('s.heroDead'),true);run('s.infirmaryPatient.until=Date.now()-1;accrue()');assert.equal(run('s.heroDead'),false);assert.equal(run('s.heroRevives'),1);assert.equal(run('s.gold+s.food'),0);assert.equal(run('s.debt'),100);assert.equal(run('s.infirmaryPatient.target'),0);run('s.infirmaryPatient.until=Date.now()-1;settleInfirmary();settleInfirmary()');assert.equal(run('s.recruits[0].dead'),false);assert.equal(run('s.recruits[0].revives'),1);assert.equal(run('admitPatient(0)'),false);});
test('infirmary construction and treatment survive JSON save migration',()=>{const run=game();run('s.projects.infirmary={stage:2,until:Date.now()+180000};s=migrate(JSON.parse(JSON.stringify(s)))');assert.equal(run('s.projects.infirmary.stage'),2);assert.ok(run('s.projects.infirmary.until')>Date.now());run('s.projects.infirmary={stage:3,until:0};s.heroDead=true;admitPatient("hero");s=migrate(JSON.parse(JSON.stringify(s)));s.infirmaryPatient.until=Date.now()-1;accrue()');assert.equal(run('s.heroDead'),false);assert.equal(run('s.infirmaryPatient'),null);});
test('weapon pool offers distinct speed, strength, and utility tradeoffs',()=>{const run=game();assert.equal(run('Object.keys(WEAPON_POOL).length'),6);const normal=run('gearItem("weapon",2,0,"balanced")'),fast=run('gearItem("weapon",2,0,"swift")'),heavy=run('gearItem("weapon",2,0,"heavy")');assert.ok(fast.stats.attack<normal.stats.attack);assert.ok(fast.stats.speed>0);assert.ok(heavy.stats.attack>normal.stats.attack);assert.ok(heavy.stats.speed<0);assert.ok(run('gearItem("weapon",2,0,"warden").stats.defense')>0);assert.ok(run('gearItem("weapon",2,0,"blood").stats.leech')>0);assert.ok(run('gearItem("weapon",2,0,"precise").stats.crit')>0);assert.notEqual(run('equipmentIcon("weapon",2,"rare","swift")'),run('equipmentIcon("weapon",2,"rare","heavy")'));});
test('weapon identity survives swaps, comparisons, upgrades and save migration',()=>{const run=game();run('s.gear.weapon=1;s.gearVariants.weapon="heavy";s.equipmentBag=[{slot:"weapon",tier:2,upgrade:0,rarity:"rare",variant:"swift"}]');const before=run('JSON.stringify(s)');assert.ok(run('itemComparison(s.equipmentBag[0]).speed')>0);assert.equal(run('JSON.stringify(s)'),before);assert.equal(run('equipItem(0)'),true);assert.equal(run('s.gearVariants.weapon'),'swift');assert.equal(run('s.equipmentBag[0].variant'),'heavy');run('s.gearUpgrades.weapon=2;s.gear.weapon=3;s=migrate(JSON.parse(JSON.stringify(s)))');assert.equal(run('gearItem("weapon").variant'),'swift');assert.match(run('gearItem("weapon").name'),/dirk/);assert.equal(run('gearItem("weapon").stats.speed'),.35);});
test('different weapon styles are not labeled duplicates',()=>{const run=game();run('s.gear.weapon=1;s.gearVariants.weapon="heavy";s.equipmentBag=[{slot:"weapon",tier:1,variant:"swift"},{slot:"weapon",tier:1,variant:"blood"}]');assert.equal(run('isDuplicate(s.equipmentBag[0],0)'),false);run('s.equipmentBag[1].variant="swift"');assert.equal(run('isDuplicate(s.equipmentBag[0],0)'),true);});
test('attack speed changes real attack counts and slow weapons skip beats',()=>{const run=game();const attacks={};run('const originalHit=hit;let countedAttacks=0;hit=(source,target)=>{if(source.id==="hero")countedAttacks++;return originalHit(source,target)}');for(const style of ['balanced','swift','heavy']){run(`countedAttacks=0;s.gear.weapon=1;s.gearVariants.weapon='${style}';startBattle({d:0,mod:1,name:'Speed test'});battle.enemies[0].hp=100000;battle.enemies[0].maxHp=100000;battle.enemies[0].attack=0;Math.random=()=>.5`);for(let i=0;i<12;i++)run('tickBattle()');attacks[style]=run('countedAttacks');}assert.ok(attacks.swift>attacks.balanced);assert.ok(attacks.heavy<attacks.balanced);assert.equal(attacks.balanced,12);assert.equal(attacks.swift,16);assert.equal(attacks.heavy,9);});

test('combat score accounts for equipment, support, combat bonuses and party eligibility without mutating saves',()=>{const run=game(),base=run('combatScore()');run('s.gear.weapon=2;s.gear.body=2;s.gear.cape=2;s.gear.neck=2;s.gear.ring=2;s.workers={wood:{xp:0},stone:{xp:0},food:{xp:0}};s.meta.prestiges=1;s.talents.warrior=1;s.recruits=[{cls:"Warrior",level:5,dead:false,loyalty:30},{cls:"Healer",level:5,dead:false}]');assert.ok(run('combatScore()')>base);const before=run('JSON.stringify(s)');assert.equal(run('combatBreakdown().reduce((sum,r)=>sum+r.value,0)'),run('combatScore()'));assert.equal(run('JSON.stringify(s)'),before);const full=run('combatScore()');run('s.objective="solo"');assert.ok(run('combatScore()')<full);run('s.objective="none";s.talents.treasure=5');assert.equal(run('combatScore()'),full);run('s.recruits[0].dead=true');assert.ok(run('combatScore()')<full);run('s.heroDead=true');assert.equal(run('combatScore()'),0);});
test('dungeon recommendations rise with difficulty and combat modifiers',()=>{const run=game();assert.ok(run('recommendedScore({d:1})')>run('recommendedScore({d:0})'));assert.ok(run('recommendedScore({d:2})')>run('recommendedScore({d:1})'));assert.ok(run('recommendedScore({d:0,modifier:"elite"})')>run('recommendedScore({d:0})'));assert.equal(run('recommendedScore({d:0,modifier:"double"})'),run('recommendedScore({d:0})'));});
test('quarters preparation replaces the original farm costs and hiring only spends gold',()=>{const run=game();run('s.buildings.barracks=1;s.wood=5000;s.stone=5000;s.food=5000;s.gold=5000');const cost=run('JSON.stringify(recruitCost())');assert.equal(run('hireRecruit("Archer")'),false);for(let i=0;i<3;i++)assert.equal(run('prepareQuarters()'),true);const c=JSON.parse(cost);assert.equal(run('s.wood'),5000-c.wood);assert.equal(run('s.stone'),5000-c.stone);assert.equal(run('s.food'),5000-c.food);assert.equal(run('s.gold'),5000);assert.equal(run('prepareQuarters()'),false);assert.equal(run('hireRecruit("Archer")'),true);assert.equal(run('s.gold'),5000-c.gold);assert.equal(run('s.quarters.stage'),0);assert.equal(run('s.recruits.length'),1);});
test('failed preparation preserves resources and completed milestones survive saves',()=>{const run=game();run('s.buildings.barracks=1;s.wood=500;s.stone=0');assert.equal(run('prepareQuarters()'),false);assert.equal(run('s.wood'),500);run('s.stone=500;prepareQuarters();s=migrate(JSON.parse(JSON.stringify(s)))');assert.equal(run('s.quarters.stage'),1);assert.match(run('blockedReason("recruit:Healer")'),/1\/3/);});
test('recovery queue defaults to hero first, can reorder waiting recruits and completes all while away',()=>{const run=game();run('s.projects.infirmary.stage=3;s.heroDead=true;s.recruits=[0,1,2].map(i=>({name:"Troop "+i,cls:"Warrior",level:1,dead:true,revives:0}));queueFallen()');assert.equal(run('s.infirmaryPatient.target'),'hero');assert.equal(run('JSON.stringify(s.recoveryQueue)'), '[0,1,2]');assert.equal(run('reorderRecovery(2,-1)'),true);assert.equal(run('JSON.stringify(s.recoveryQueue)'), '[0,2,1]');assert.equal(run('reorderRecovery(0,-1)'),false);run('s=migrate(JSON.parse(JSON.stringify(s)));s.infirmaryPatient.until=Date.now()-180001;settleInfirmary();settleInfirmary()');assert.equal(run('s.infirmaryPatient'),null);assert.equal(run('s.recoveryQueue.length'),0);assert.equal(run('s.heroDead'),false);assert.equal(run('s.heroRevives'),1);assert.equal(run('s.recruits.every(r=>!r.dead&&r.revives===1)'),true);});
test('rush treatment gets cheaper with remaining time and starts next patient with a fresh minute',()=>{const run=game();run('s.projects.infirmary.stage=3;s.heroDead=true;s.recruits=[{cls:"Warrior",level:1,dead:true}];queueFallen()');const start=run('rushCost().gold');run('s.infirmaryPatient.until=Date.now()+30000');assert.ok(run('rushCost().gold')<start);const cost=run('JSON.stringify(rushCost())');assert.equal(run('rushRecovery()'),false);run('s.gold=100;s.food=100');assert.equal(run('rushRecovery()'),true);assert.equal(run('s.gold'),100-JSON.parse(cost).gold);assert.equal(run('s.food'),100-JSON.parse(cost).food);assert.equal(run('s.heroDead'),false);assert.equal(run('s.infirmaryPatient.target'),0);assert.ok(run('s.infirmaryPatient.until-Date.now()')>59000);assert.equal(run('s.heroRevives'),1);});
test('fractional life steal is proportional to actual damage rather than healing once per small hit',()=>{const run=game();run('startBattle({d:0,name:"Leech"});const source={id:"hero",name:"Hero",role:"Hero",attack:1,crit:0,leech:.025,hp:20,maxHp:100};const victim={id:"enemy",name:"Enemy",role:"Warrior",hp:100,maxHp:100,defense:0,evade:0};Math.random=()=>.5;for(let i=0;i<10;i++)hit(source,victim)');assert.ok(Math.abs(run('source.hp')-20.25)<1e-8);assert.ok(Math.abs(run('battle.stats.healing.hero')-.25)<1e-8);});
test('base and other-slot damage are normalized so speed does not multiply an entire loadout',()=>{const run=game();run('s.gear.weapon=2;s.gear.neck=2;s.gear.hands=2;s.gear.ring=2');const scores=[];for(const style of ['balanced','swift','heavy']){run(`s.gearVariants.weapon='${style}'`);scores.push(run('heroStats().attack*(1+heroStats().speed)'));}assert.ok(Math.max(...scores)/Math.min(...scores)<1.12);});
test('tracked goals follow spare identities through equipping and guide route focus',()=>{const run=game();run('s.equipmentBag=[{slot:"weapon",tier:2,upgrade:0,rarity:"rare",variant:"heavy"}];pinSpare(0)');assert.match(run('goalDetails().name'),/maul/);assert.match(run('goalRecommendation()'),/Materials route/);const id=run('s.pinnedGoal.itemId');assert.equal(run('s.equipmentBag[0].id'),id);run('s=migrate(JSON.parse(JSON.stringify(s)));equipItem(0)');assert.equal(run('s.pinnedGoal.kind'),'upgrade');assert.equal(run('s.pinnedGoal.slot'),'weapon');assert.match(run('goalDetails().name'),/maul/);});
test('material tooltips, unavailable actions and debriefs explain sources and next steps',()=>{const run=game();assert.match(run('materialTooltip("leather")'),/Materials focus/);assert.match(run('blockedReason("recruit:Warrior")'),/Requires barracks/);assert.match(run('blockedReason("storage:wood")'),/Missing 35 wood/);run('s.buildings.barracks=1;pinGoal("infirmary")');assert.match(run('goalRecommendation()'),/infirmary.*more Iron/i);run('s.wood=5000;s.stone=5000;s.food=5000;s.gold=5000;for(const key of Object.keys(s.items))s.items[key]=100');assert.match(run('nextDecision(true)'),/supplies for Infirmary/);run('s.pinnedGoal=null;s.heroDead=true;s.food=0;s.gold=0');assert.match(run('nextDecision(false)'),/Gather food/);});

test('small hero hits avoid whole-HP minimum abuse while enemies retain their original damage floor',()=>{const run=game();run('startBattle({d:0,name:"Armor test"});Math.random=()=>.5;const strongArmor={id:"enemy",name:"Armored",role:"Warrior",hp:100,maxHp:100,defense:100};const weakHero={id:"hero",name:"Hero",role:"Hero",hp:100,maxHp:100,attack:1,crit:0};hit(weakHero,strongArmor)');assert.equal(run('strongArmor.hp'),99.9);run('weakHero.defense=100;strongArmor.attack=1;strongArmor.crit=0;hit(strongArmor,weakHero)');assert.equal(run('weakHero.hp'),99);});
