import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {readFileSync} from 'node:fs';
import path from 'node:path';
test('standalone mode works from one HTML without external requests',async()=>{
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
try{const page=await browser.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url()!=='http://standalone.test/')requests.push(r.url())});
// Managed Chromium blocks file URLs here; serve the unchanged inline assets
// with standalone mode selected to validate offline behavior.
const html=readFileSync(path.resolve('public/index.html'),'utf8').replace("const standalone=location.protocol==='file:';",'const standalone=true;');
await page.route('http://standalone.test/',r=>r.fulfill({contentType:'text/html',body:html}));await page.goto('http://standalone.test/');await page.clock.install();await page.getByRole('button',{name:'Understood'}).click();await page.getByRole('button',{name:'Gather wood',exact:true}).click();await page.clock.runFor(9000);await page.getByRole('button',{name:'Collect +12'}).click();assert.match(await page.locator('.resource').first().innerText(),/12/);await page.reload();assert.match(await page.locator('.resource').first().innerText(),/12/);await page.locator('[data-action="account"]').click();assert.match(await page.locator('#account').innerText(),/Local adventure/);await page.locator('#account [data-action="close"]').click();await page.locator('[data-action="settings"]').click();await page.locator('[data-action="reset-prompt"]').click();await page.locator('[data-action="settings"]').last().click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('gravehold')).wood),12);await page.locator('[data-action="reset-prompt"]').click();await page.locator('#reset-word').fill('RESET');await page.locator('[data-action="reset-confirm"]').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('gravehold')).wood),0);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
}finally{await browser.close()}
});

test('resource explanations, foreman, tutorial opt-out, offline queue, talents, and prestige UI',async()=>{
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();
const html=readFileSync(path.resolve('public/index.html'),'utf8').replace("const standalone=location.protocol==='file:';",'const standalone=true;');await page.route('http://advanced.test/',r=>r.fulfill({contentType:'text/html',body:html}));await page.goto('http://advanced.test/');await page.locator('#tutorials-off').check();await page.getByRole('button',{name:'Understood'}).click();
await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('gravehold'));s.wood=380;s.stone=400;s.food=400;s.workers={wood:{xp:0},stone:{xp:0},food:{xp:0}};s.buildings={wood:1,stone:1,food:1,woodStorage:2,stoneStorage:2,foodStorage:2};localStorage.setItem('gravehold',JSON.stringify(s));});await page.reload();assert.equal(await page.locator('#journal').evaluate(d=>d.open),false);await page.locator('.resource').first().hover();assert.equal(await page.locator('#resource-tip-wood').isVisible(),true);assert.match(await page.locator('#resource-tip-wood').innerText(),/builds sites/);assert.match(await page.locator('.resource').first().innerText(),/380\/400/);assert.match(await page.locator('.capacity-warning').first().innerText(),/nearly full/);await page.mouse.move(0,0);await page.locator('.storage-info summary').first().click();assert.match(await page.locator('.storage-info').first().innerText(),/400 → 550/);await page.locator('[data-panel="settlement-milestones"]>summary').click();await page.locator('[data-action="foreman"]').click();await page.getByRole('button',{name:'Gather wood',exact:true}).click();await page.clock.runFor(9000);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('gravehold')).gather),null);await page.screenshot({path:'/tmp/gravehold-resource-ui.png',fullPage:true});
await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('gravehold'));s.gear.weapon=100;s.gear.body=100;s.meta.essence=5;s.cycleBosses=1;s.history.bosses=1;s.clearedDungeons[0]={d:0,mod:1,modifier:'none',name:'Cleared crypt'};localStorage.setItem('gravehold',JSON.stringify(s));});await page.reload();await page.locator('[data-tab="Expeditions"]').click();assert.equal(await page.locator('#journal').evaluate(d=>d.open),false);await page.locator('.queue-panel summary').click();await page.locator('[data-action="queue:0"]').click();await page.clock.runFor(301500);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('gravehold')).offlineQueue),null);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('gravehold')).history.runs),1);await page.locator('[data-tab="Progression"]').click();await page.locator('[data-action="talent:warrior"]').click();await page.screenshot({path:'/tmp/gravehold-progression.png',fullPage:true});await page.locator('[data-action="prestige-prompt"]').click();await page.locator('[data-action="prestige-confirm"]').click();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('gravehold')));assert.equal(state.meta.prestiges,1);assert.equal(state.talents.warrior,1);assert.equal(state.history.runs,1);assert.equal(state.gear.weapon,-1);await page.reload();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('gravehold')).meta.prestiges),1);assert.deepEqual(errors,[]);
}finally{await browser.close()}
});

test('armory new finds support dismissal, ranked slot equipment, and salvage without inventory',async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const html=readFileSync('public/index.html','utf8').replace("const standalone=location.protocol==='file:';",'const standalone=true;');await page.route('http://armory.test/',r=>r.fulfill({contentType:'text/html',body:html}));await page.goto('http://armory.test/');await page.getByRole('button',{name:'Understood'}).click();await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('gravehold'));s.tutorialsDisabled=true;s.gear.weapon=1;s.equipmentBag=[{slot:'weapon',tier:0,rarity:'legendary'},{slot:'weapon',tier:2,rarity:'rare'},{slot:'head',tier:1,rarity:'common'}];localStorage.setItem('gravehold',JSON.stringify(s));});await page.reload();await page.locator('[data-tab="Loadout"]').click();assert.equal(await page.locator('.item-detail').count(),0);assert.equal(await page.locator('.new-finds .armory-find').count(),3);await page.locator('[data-action="slot:weapon"]').click();assert.equal(await page.locator('.new-finds .armory-find').count(),3);assert.match(await page.locator('.slot-options .armory-find').first().innerText(),/Gravewarden/);assert.match(await page.locator('.slot-options .armory-find').last().innerText(),/−6 attack/);await page.locator('.new-finds [data-action="dismiss:2"]').click();assert.equal(await page.locator('.new-finds .armory-find').count(),2);await page.reload();await page.locator('[data-tab="Loadout"]').click();assert.equal(await page.locator('.new-finds .armory-find').count(),2);await page.locator('.new-finds [data-action="equip:1"]').click();assert.equal(await page.locator('.new-finds .armory-find').count(),1);await page.locator('.new-finds [data-action="salvage:0"]').click();await page.locator('#salvage [data-action="close"]').click();assert.equal(await page.locator('.new-finds .armory-find').count(),1);await page.locator('.new-finds [data-action="salvage:0"]').click();await page.locator('[data-action="salvage-confirm"]').click();assert.equal(await page.locator('.new-finds .armory-find').count(),0);assert.equal(await page.locator('#inventory').evaluate(d=>d.open),false);await page.screenshot({path:'/tmp/armory-centered.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);}finally{await browser.close();}
});
